/*******************************************************************************
* Copyright (c) 2007 MediaTek Inc.
*
* All rights reserved. Copying, compilation, modification, distribution
* or any other use whatsoever of this material is strictly prohibited
* except in accordance with a Software License Agreement with
* MediaTek Inc.
********************************************************************************
*/
/*******************************************************************************
* LEGAL DISCLAIMER
*
* BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND
* AGREES THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK
* SOFTWARE") RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE
* PROVIDED TO BUYER ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY
* DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT
* LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
* PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE
* ANY WARRANTY WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY
* WHICH MAY BE USED BY, INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK
* SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY
* WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE
* FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION OR TO
* CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
* BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
* LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL
* BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT
* ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY
* BUYER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
* THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
* WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT
* OF LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING
* THEREOF AND RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN
* FRANCISCO, CA, UNDER THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE
* (ICC).
********************************************************************************
*/
#ifndef _LED_CTRL_H
#define _LED_CTRL_H
#ifdef LED_CONTROL_SUPPORT

/*******************************************************************************
*						 C O M P I L E R   F L A G S
********************************************************************************
*/


enum LED_TIMEOUT_STATUS {
	LED_TIMEOUT_NONE,
	LED_TIMEOUT_WPS_SUCCESS_ON_5S_OFF_3S,
	LED_TIMEOUT_WPS_SUCCESS_ON_5S_OFF_3S_TX_BLINK,
	LED_TIMEOUT_WPS_SUCCESS_ON_5S_OFF,
};

typedef enum _ENUM_LED_CTRL_T {
	ENUM_LED_BEHAVIOR_SOLID_ON						= 0,
	ENUM_LED_BEHAVIOR_SOLID_OFF					   = 1,
	ENUM_LED_BEHAVIOR_BLINKING_TX_MAC				 = 2,
	ENUM_LED_BEHAVIOR_BLINKING_1_BLINK_PER_SEC		= 3,
	ENUM_LED_BEHAVIOR_BLINKING_2_BLINK_PER_SEC		= 4,
	ENUM_LED_BEHAVIOR_BLINKING_3_BLINK_PER_SEC		= 5,
	ENUM_LED_BEHAVIOR_BLINKING_500MS_ON_100MS_OFF	 = 6,
	ENUM_LED_BEHAVIOR_WPS_3_BLINK_FOR_4_SEC		   = 16,
	ENUM_LED_BEHAVIOR_WPS_5S_ON_3S_OFF_THEN_BLINKG_TX = 17,
	ENUM_LED_BEHAVIOR_WPS_5S_ON					   = 18,
	ENUM_LED_BEHAVIOR_GENERIC_FIX_BLINKING			= 31,
	ENUM_LED_BEHAVIOR_OTHER_BLINKING_INTERACTIVE	  = 32
} ENUM_LED_CTRL_T, *P_ENUM_LED_CTRL_T;

/*******************************************************************************
*					E X T E R N A L   R E F E R E N C E S
********************************************************************************
*/

typedef struct _LED_EVENT {
	PRTMP_ADAPTER pAd;
	ULONG u4LedNo;		/* TxBuf virtual address */
} LED_EVENT;

extern INT hemExtCmdLedCtrl(
	IN PRTMP_ADAPTER pAd,
	IN UCHAR u4LedNo,
	IN UCHAR ucOnTime,
	IN UCHAR ucOffTime,
	IN UCHAR Led_Parameter
);
extern VOID ledCrInit(VOID);

#endif /* LED_CONTROL_SUPPORT */
#endif /* _LED_CTRL_H */

